server:
  port: 8080
spring:
  application:
    name: app-user
  datasource:
    name: mysql-datasource
    type: org.apache.commons.dbcp2.BasicDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shersfy?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 123456
