version: 1.0.0
spring:
  datasource:
    name: mysql-datasource
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      register-mbeans: true
      pool-name: hikari-pool
      driver-class-name: com.mysql.jdbc.Driver
      jdbc-url: jdbc:mysql://168.5.80.93:3306/datahub_job_manager?useUnicode=true&characterEncoding=utf8&useSSL=false
      username: domeos
      password: domeos
  quartz:
    job-store-type: jdbc
    jobCodePrefix: job
    # once immediately jobs run thread pool size
    jobSubthreadSize: 500
    jobDispatchTimeoutSeconds: 60
    properties:
      org:
        quartz:
          scheduler:
            instanceName: DefaultQuartzScheduler
            instanceId: AUTO
            rmi:
              export: false
              proxy: false
            wrapJobExecutionInUserTransaction: false
          threadPool:
            class: org.quartz.simpl.SimpleThreadPool
            threadCount: 500
            threadPriority: 5
            threadsInheritContextClassLoaderOfInitializingThread: true
          jobStore: 
            class: org.quartz.impl.jdbcjobstore.JobStoreTX
            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
            misfireThreshold: 60000
            useProperties: false
            dataSource: myDS
            tablePrefix: QRTZ_
            isClustered: true
            clusterCheckinInterval: 20000
# hystrix 必须加否则无效(默认false)
feign: 
  hystrix:
    enabled: true
# 配置没生效
ribbon:
    ReadTimeout: 5000
    ConnectTimeout: 5000
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false
        isolation:
          strategy: THREAD
          thread:
            timeoutInMilliseconds: 5000
# management
management:
  endpoints:
    web:
      exposure:
        include: refresh, bus-refresh
# i18n
i18n:
  file-encoding: UTF-8
  locations: classpath:i18n/*.properties
# mybatis
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: org.shersfy.datahub.jobmanager.model
# logging
logging:
  file: logs/${spring.application.name}.log
  level:
    root: info
  pattern:
    dateformat: yyyy-MM-dd HH:mm:ss.SSS
    level: '%5p'
